### ISSUE TITLE
Veraltete Composer Dependencies

### ISSUE THREAD

**Issue by mmodler** [Nordkirche/NDK#6]
Hallo,

wir evaluieren gerade, ob wir den NDK nutzen können für unsere Integration in ChurchTools Website.

Der NDK nutzt jedoch einige ältere composer Dependencies, welche in unserem Projekt zu Konfikten führen:

doctrine/cache ^1.6 - wir brauchen 2.2
guzzlehttp/guzzle ^6.2 - wir brauchen ^7.2

Besteht die Möglichkeit die Dependencies zu updaten, oder einen 2.x Brach bereitzustellen, der die aktuellen Dependencies enthält (schön wäre alle PHP 8 kompatibel)

Danke!

**Comment by hmccloy** [comment]
Moin,
ja, es geht in Kürze die Arbeit an der neuen Version los. Dann werden auch die Dependencies für PHP 8.x aktualisiert.

Viele Grüße
Holger

**Comment by hmccloy** [comment]
Moin,
ja, es geht in Kürze die Arbeit an der neuen Version los. Dann werden auch die Dependencies für PHP 8.x aktualisiert.

Viele Grüße
Holger

**Comment by hmccloy** [comment]
Version 2.0 mit aktuellen dependencies ist released.
